FROM php:8.2-apache

# Disable interaction
ENV DEBIAN_FRONTEND=noninteractive

# Basic update and install
RUN set -ex && apt-get update && apt-get install -y \
    libpq-dev \
    vim

# Install php extension
RUN docker-php-ext-install pdo pdo_pgsql

# Clean
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
